### PR TITLE
cog example (fixed)

### PR DESCRIPTION
**Pull request by yonipy**
## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, ...)

### CODE REVIEW

**Comment by ysIgnacio** [comment]
why u remove almost everything

**Comment by yonipy** [comment]
i removed half the files mb ill revert brb

**Comment by EnokiUN** [comment]
What the fuck.



I suppose.

**Comment by EnokiUN** [comment]
Can we close this issue and start a new.... unfucked one I suppose.

**Pull request closed without merging**
