### PR TITLE
Update api.rst

### PR DESCRIPTION
**Pull request by ksIsCute**
typo

## Checklist

- [ ] If code changes were made then they have been tested.
    - [ ] I have updated the documentation to reflect the changes.
- [ ] This PR fixes an issue.
- [ ] This PR adds something new (e.g. new method or parameters).
- [ ] This PR is a breaking change (e.g. methods or parameters removed/renamed)
- [x] This PR is **not** a code change (e.g. documentation, README, …)

### CODE REVIEW

**Comment by ksIsCute** [comment]
@b1ue64

**Comment by b1ue64** [comment]
i also did this smh

**Comment by b1ue64** [comment]
wait you did it first nvm

**Comment by ksIsCute** [comment]
:trollface: kek

**Pull request merged**
